### ISSUE TITLE
Permissions on ~/.netrc can drift away from 600

### ISSUE THREAD

**Issue by sammarcus** [flatiron-school/environmentalizer#15]
After running Learn setup process on OS X with no errors multiple users have reported that `.netrc` permissions are 644 where they should be 600 (looks like that's full read/write access).

Issue is revealed upon running `Learn` gem. This does not necessarily happen immediately after setup; somehow the permissions have been changed even after running `Learn` successfully before.

Problem can be fixed through simple `chmod 600 ~/.netrc`. 

cc @loganhasson

**Comment by loganhasson** [comment]
@sammarcus solved in most recent version of osx app that will be released today/tomorrow. let me know if it pops up again!
