### ISSUE TITLE
Sublime Text symlink creates a "bin" symlink in /usr/local to subl when the /usr/local/bin dir doesnt exist

### ISSUE THREAD

**Issue by spencer1248** [flatiron-school/environmentalizer#22]
When homebrew fails to install and there is no /usr/local/bin, the line below will symlink a file called "bin" to subl and prevent homebrew from installing correctly

https://github.com/flatiron-school/environmentalizer/blob/0f63b3a48f63abd55dda9956de309b201d5ddb12/shared/sublime_symlink/install.sh#L12

**Comment by loganhasson** [comment]
updated to add a trailing slash so that it at least doesn't create a 'bin' symlink

**Comment by loganhasson** [comment]
should be fixed
