### ISSUE TITLE
Issue with downloading

### ISSUE THREAD

**Issue by AlexanderDubois** [flatiron-school/environmentalizer#25]
When I write $ ./install.sh /usr/local for installing I receive this message:

mkdir: /usr/local/bin: Permission denied
mkdir: /usr/local/libexec: Permission denied
mkdir: /usr/local/share/man/man1: Permission denied
mkdir: /usr/local/share/man/man7: Permission denied

When I tried the $ bats test command I received this:
-bash: bats: command not found

What is wrong? Please help!:)

**Comment by aviflombaum** [comment]
Hi @AlexanderDubois 

We're not really supporting installing this script manually anymore. Based on your errors though, my guess is you must `sudo`.

```bash
$ sudo ./install.sh /usr/local 
```

Try that. But you should really use the OS X app to run this through, it's way better: https://learn.co/tools ( https://flatironschool-static.s3.amazonaws.com/learn.dmg )
