### ISSUE TITLE
rvm check isn't right

### ISSUE THREAD

**Issue by loganhasson** [flatiron-school/environmentalizer#28]
think there are too many conditions in the if block. probably should separate it into multiple if statements

**Comment by matbalez** [comment]
Let's prioritize this upon your return Logan.

**Comment by loganhasson** [comment]
@matbalez this should be fixed. can you confirm by running `learn doctor` on your machine (or by viewing the setup summary in the os x app)?

**Comment by matbalez** [comment]
Yep.
