### ISSUE TITLE
Sublime error on first use after running environmentalizer

### ISSUE THREAD

**Issue by matbalez** [flatiron-school/environmentalizer#9]
A student reports: 

After running the environmentalizer tool, I received an error from Sublime Text that it couldn't load the color scheme, which appeared to have been reset to a custom Flatiron scheme. Works fine after I manually adjust the color setting through Sublime Preferences, but just noting.

It doesn't give me the error again on re-opening, and I did not think to copy the exact text of the error before messing around with colors to try to fix it.

**Comment by TSiege** [comment]
This was an error from the https://github.com/flatiron-school/dotfiles requiring a directory, which in several cases did not exist.
